package net.sf.javascribe.api;

/**
 * Represents a source file generated by a Javascribe component processor.  
 * The file must support set/get of a path, as well as an API for retrieving 
 * the source code.
 * @author DCS
 */
public interface SourceFile {

	/**
	 * Returns the source code for this file.  The framework will not invoke 
	 * this until all components have been processed.
	 * @return Source as it will be put into the file.
	 * @throws JavascribeException If there is a problem getting the source code.
	 */
	public StringBuilder getSource() throws JavascribeException;
	
	/**
	 * Query the file for its absolute path.
	 * @return Absolute file system path.
	 */
	public String getPath();
	
	/**
	 * Set the absolute path for this generated file.
	 * @param path Absolute path.
	 */
	public void setPath(String path);
	
}

